sudo: false
language: python
python:
  - "2.6"
  - "2.7"
before_install:
  - pip install --upgrade pip
install:
  - pip install -U pip
  - pip install -U setuptools
  - pip install pycodestyle
  - python setup.py install
script:
  - python setup.py test
  - pycodestyle
after_success:
  - coveralls